version: '3'

services:

  db:
    image: mongo
    ports:
      - "27017:27017"

  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data_a:/data
    entrypoint: redis-server --appendonly yes


  backend:
    build:
      context: ..
    image: MAIN_PROJECT
    command: gunicorn PROJECT.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - staticc:/django/EXTRAS/static  # Mount the static files directory
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./nginx/nginx-setup.conf:/etc/nginx/conf.d/default.conf:ro
      - staticc:/var/www/staticfiles  # Mount the static files directory
    depends_on:
      - backend
      - db
      - redis


volumes:
  staticc:
  redis-data_a:
